version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
branches:
  only:
  - master
  - dev
  - v2.x
clone_folder: c:\azure-webjobs-sdk-extensions
environment:
  BUILD_NUMBER: '%APPVEYOR_BUILD_NUMBER%'
  IncludeBuildNumberInVersion: 1
build_script:
- cmd: IF "%APPVEYOR_REPO_TAG_NAME%"=="" SET PackageSuffixCmd=/p:PackageSuffix=-%APPVEYOR_BUILD_NUMBER%
- cmd: msbuild "WebJobs.Extensions.proj" /target:EnableSkipStrongNames;TestBuild /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /property:BuildNumber=%APPVEYOR_BUILD_NUMBER%;Configuration=Release %PackageSuffixCmd%
artifacts:
- path: bin\Packages\*.*
  name: Packages